//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Observer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLogs
    {
        public int IdLog { get; set; }
        public Nullable<System.DateTime> TimeStampLog { get; set; }
        public string Details { get; set; }
    }
}
