//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Observer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_localEntities : DbContext
    {
        public db_localEntities()
            : base("name=db_localEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLogs> AccessLogs { get; set; }
        public virtual DbSet<AccessRights> AccessRights { get; set; }
        public virtual DbSet<ListOfChanges> ListOfChanges { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
