//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Device_Observer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAU
    {
        public int IdUserAU { get; set; }
        public string LoginUserAU { get; set; }
        public string PasswordUserAU { get; set; }
        public string RoleUser { get; set; }
        public string Details { get; set; }
    }
}
